### ISSUE TITLE
Create a PR Template and an Issue Template to make contributing easier

### ISSUE THREAD

**Issue by john0isaac** [render-engine/render-engine-parser#10]
We need to create a pull request template and issue templates for this repo to make contributing to it easier.

You may reference the templates at the main [render engine](https://github.com/render-engine/render-engine) repo to help you.

We only need to create templates here just like the ones on the main repo.

**Comment by JohananOppongAmoateng** [comment]
Can I get assigned to this

**Comment by john0isaac** [comment]
Sure

**Comment by JohananOppongAmoateng** [comment]
@john0isaac submitted a pr for this
